### ISSUE TITLE
Eclude incompatible Api level does not work

### ISSUE THREAD

**Issue by tetsuo55** [rumboalla/apkupdater#222]
Iirc this is because the apkmirror api needs to be updated.

Opened this ticket to track the issue

**Comment by rumboalla** [comment]
As far as I know this was fixed.

**Comment by tetsuo55** [comment]
No its still broken.

Uncheck exclude architecture to see it

**Comment by rumboalla** [comment]
Provide examples then.

**Comment by tetsuo55** [comment]
Examples on xda https://forum.xda-developers.com/showpost.php?p=73006520&postcount=369

**Comment by rumboalla** [comment]
Ok, fixed this now.

**Comment by tetsuo55** [comment]
Great and extra thanks for the fast responce

**Comment by tetsuo55** [comment]
Unfortunately it is still broken in the new release.

I am getting this package on my api24 galaxy s7

https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-o-release/package-installer-o-android-apk-download/

**Comment by rumboalla** [comment]
Looks like wrong data from server. It says minapi-O instead of 26.

**Comment by tetsuo55** [comment]
Do you have a way to get that corrected? There are actually a few more with this issue

**Comment by rumboalla** [comment]
I added a fix to convert it to the proper api level, so it should be fine now.

**Comment by tetsuo55** [comment]
What about this one?
https://www.apkmirror.com/apk/google-inc/setup-wizard/setup-wizard-226-release/setup-wizard-226-android-apk-download/

I dont think thats safe to install
